;;; © vyzo
;;; cairo namespace

(namespace ("vyzo/cairo#"
            CAIRO_FILL_RULE_WINDING
            CAIRO_FILL_RULE_EVEN_ODD
            CAIRO_LINE_CAP_BUTT
            CAIRO_LINE_CAP_ROUND
            CAIRO_LINE_CAP_SQUARE
            CAIRO_LINE_JOIN_MITER
            CAIRO_LINE_JOIN_ROUND
            CAIRO_LINE_JOIN_BEVEL
            CAIRO_OPERATOR_CLEAR
            CAIRO_OPERATOR_SOURCE
            CAIRO_OPERATOR_OVER
            CAIRO_OPERATOR_IN
            CAIRO_OPERATOR_OUT
            CAIRO_OPERATOR_ATOP
            CAIRO_OPERATOR_DEST
            CAIRO_OPERATOR_DEST_OVER
            CAIRO_OPERATOR_DEST_IN
            CAIRO_OPERATOR_DEST_OUT
            CAIRO_OPERATOR_DEST_ATOP
            CAIRO_OPERATOR_XOR
            CAIRO_OPERATOR_ADD
            CAIRO_OPERATOR_SATURATE
            cairo-create
            cairo-reference
            cairo-destroy
            cairo-status
            cairo-save
            cairo-restore
            cairo-get-target
            cairo-push-group
            cairo-push-group-with-content
            cairo-pop-group
            cairo-pop-group-to-source
            cairo-get-group-target
            cairo-set-source-rgb
            cairo-set-source-rgba
            cairo-set-source
            cairo-set-source-surface
            cairo-get-source
            cairo-set-antialias
            cairo-get-antialias
            cairo-set-dash
            cairo-get-dash-count
            cairo-get-dash
            cairo-set-fill-rule
            cairo-get-fill-rule
            cairo-set-line-cap
            cairo-get-line-cap
            cairo-set-line-join
            cairo-get-line-join
            cairo-set-line-width
            cairo-get-line-width
            cairo-set-miter-limit
            cairo-get-miter-limit
            cairo-set-operator
            cairo-get-operator
            cairo-set-tolerance
            cairo-get-tolerance
            cairo-clip
            cairo-clip-preserve
            cairo-clip-extents
            cairo-reset-clip
            cairo-rectangle-list-destroy
            cairo-copy-clip-rectangle-list
            cairo-fill
            cairo-fill-preserve
            cairo-fill-extents
            cairo-in-fill
            cairo-mask
            cairo-mask-surface
            cairo-paint
            cairo-paint-with-alpha
            cairo-stroke
            cairo-stroke-preserve
            cairo-stroke-extents
            cairo-in-stroke
            cairo-copy-page
            cairo-show-page
            cairo-get-reference-count
            cairo-set-user-data
            cairo-get-user-data
            CAIRO_FONT_TYPE_TOY
            CAIRO_FONT_TYPE_FT
            CAIRO_FONT_TYPE_WIN32
            CAIRO_FONT_TYPE_QUARTZ
            CAIRO_FONT_TYPE_USER
            cairo-font-face-reference
            cairo-font-face-destroy
            cairo-font-face-status
            cairo-font-face-get-type
            cairo-font-face-get-reference-count
            cairo-font-face-set-user-data
            cairo-font-face-get-user-data
            CAIRO_SUBPIXEL_ORDER_DEFAULT
            CAIRO_SUBPIXEL_ORDER_RGB
            CAIRO_SUBPIXEL_ORDER_BGR
            CAIRO_SUBPIXEL_ORDER_VRGB
            CAIRO_SUBPIXEL_ORDER_VBGR
            CAIRO_HINT_STYLE_DEFAULT
            CAIRO_HINT_STYLE_NONE
            CAIRO_HINT_STYLE_SLIGHT
            CAIRO_HINT_STYLE_MEDIUM
            CAIRO_HINT_STYLE_FULL
            CAIRO_HINT_METRICS_DEFAULT
            CAIRO_HINT_METRICS_OFF
            CAIRO_HINT_METRICS_ON
            cairo-font-options-create
            cairo-font-options-copy
            cairo-font-options-destroy
            cairo-font-options-status
            cairo-font-options-merge
            cairo-font-options-hash
            cairo-font-options-equal
            cairo-font-options-set-antialias
            cairo-font-options-get-antialias
            cairo-font-options-set-subpixel-order
            cairo-font-options-get-subpixel-order
            cairo-font-options-set-hint-style
            cairo-font-options-get-hint-style
            cairo-font-options-set-hint-metrics
            cairo-font-options-get-hint-metrics
            cairo-ft-font-face-create-for-ft-face
            cairo-ft-font-face-create-for-pattern
            cairo-ft-font-options-substitute
            cairo-ft-scaled-font-lock-face
            cairo-ft-scaled-font-unlock-face
            CAIRO_FORMAT_ARGB32
            CAIRO_FORMAT_RGB24
            CAIRO_FORMAT_A8
            CAIRO_FORMAT_A1
            cairo-image-surface-create
            cairo-image-surface-create-for-data
            cairo-image-surface-get-data
            cairo-image-surface-get-format
            cairo-image-surface-get-width
            cairo-image-surface-get-height
            cairo-image-surface-get-stride
            cairo-matrix-init
            cairo-matrix-init-identity
            cairo-matrix-init-translate
            cairo-matrix-init-scale
            cairo-matrix-init-rotate
            cairo-matrix-translate
            cairo-matrix-scale
            cairo-matrix-rotate
            cairo-matrix-invert
            cairo-matrix-multiply
            cairo-matrix-transform-distance
            cairo-matrix-transform-point
            CAIRO_PATH_MOVE_TO
            CAIRO_PATH_LINE_TO
            CAIRO_PATH_CURVE_TO
            CAIRO_PATH_CLOSE_PATH
            cairo-copy-path
            cairo-copy-path-flat
            cairo-path-destroy
            cairo-append-path
            cairo-get-current-point
            cairo-new-path
            cairo-new-sub-path
            cairo-close-path
            cairo-arc
            cairo-arc-negative
            cairo-curve-to
            cairo-line-to
            cairo-move-to
            cairo-rectangle
            cairo-glyph-path
            cairo-text-path
            cairo-rel-curve-to
            cairo-rel-line-to
            cairo-rel-move-to
            CAIRO_EXTEND_NONE
            CAIRO_EXTEND_REPEAT
            CAIRO_EXTEND_REFLECT
            CAIRO_EXTEND_PAD
            CAIRO_FILTER_FAST
            CAIRO_FILTER_GOOD
            CAIRO_FILTER_BEST
            CAIRO_FILTER_NEAREST
            CAIRO_FILTER_BILINEAR
            CAIRO_FILTER_GAUSSIAN
            CAIRO_PATTERN_TYPE_SOLID
            CAIRO_PATTERN_TYPE_SURFACE
            CAIRO_PATTERN_TYPE_LINEAR
            CAIRO_PATTERN_TYPE_RADIAL
            cairo-pattern-add-color-stop-rgb
            cairo-pattern-add-color-stop-rgba
            cairo-pattern-get-color-stop-count
            cairo-pattern-get-color-stop-rgba
            cairo-pattern-create-rgb
            cairo-pattern-create-rgba
            cairo-pattern-get-rgba
            cairo-pattern-create-for-surface
            cairo-pattern-get-surface
            cairo-pattern-create-linear
            cairo-pattern-get-linear-points
            cairo-pattern-create-radial
            cairo-pattern-get-radial-circles
            cairo-pattern-reference
            cairo-pattern-destroy
            cairo-pattern-status
            cairo-pattern-set-extend
            cairo-pattern-get-extend
            cairo-pattern-set-filter
            cairo-pattern-get-filter
            cairo-pattern-set-matrix
            cairo-pattern-get-matrix
            cairo-pattern-get-type
            cairo-pattern-get-reference-count
            cairo-pattern-set-user-data
            cairo-pattern-get-user-data
            cairo-pdf-surface-create
            cairo-pdf-surface-create-for-stream
            cairo-pdf-surface-set-size
            cairo-image-surface-create-from-png
            cairo-image-surface-create-from-png-stream
            cairo-surface-write-to-png
            cairo-surface-write-to-png-stream
            CAIRO_PS_LEVEL_2
            CAIRO_PS_LEVEL_3
            cairo-ps-surface-create
            cairo-ps-surface-create-for-stream
            cairo-ps-surface-set-size
            cairo-ps-surface-dsc-begin-setup
            cairo-ps-surface-dsc-begin-page-setup
            cairo-ps-surface-dsc-comment
            cairo-scaled-font-create
            cairo-scaled-font-reference
            cairo-scaled-font-destroy
            cairo-scaled-font-status
            cairo-scaled-font-extents
            cairo-scaled-font-text-extents
            cairo-scaled-font-glyph-extents
            cairo-scaled-font-get-font-face
            cairo-scaled-font-get-font-options
            cairo-scaled-font-get-font-matrix
            cairo-scaled-font-get-ctm
            cairo-scaled-font-get-type
            cairo-scaled-font-get-reference-count
            cairo-scaled-font-set-user-data
            cairo-scaled-font-get-user-data
            CAIRO_CONTENT_COLOR
            CAIRO_CONTENT_ALPHA
            CAIRO_CONTENT_COLOR_ALPHA
            CAIRO_SURFACE_TYPE_IMAGE
            CAIRO_SURFACE_TYPE_PDF
            CAIRO_SURFACE_TYPE_PS
            CAIRO_SURFACE_TYPE_XLIB
            CAIRO_SURFACE_TYPE_XCB
            CAIRO_SURFACE_TYPE_GLITZ
            CAIRO_SURFACE_TYPE_QUARTZ
            CAIRO_SURFACE_TYPE_WIN32
            CAIRO_SURFACE_TYPE_BEOS
            CAIRO_SURFACE_TYPE_DIRECTFB
            CAIRO_SURFACE_TYPE_SVG
            CAIRO_SURFACE_TYPE_OS2
            CAIRO_SURFACE_TYPE_WIN32_PRINTING
            CAIRO_SURFACE_TYPE_QUARTZ_IMAGE
            cairo-surface-create-similar
            cairo-surface-reference
            cairo-surface-destroy
            cairo-surface-status
            cairo-surface-finish
            cairo-surface-flush
            cairo-surface-get-font-options
            cairo-surface-get-content
            cairo-surface-mark-dirty
            cairo-surface-mark-dirty-rectangle
            cairo-surface-set-device-offset
            cairo-surface-get-device-offset
            cairo-surface-set-fallback-resolution
            cairo-surface-get-type
            cairo-surface-get-reference-count
            cairo-surface-set-user-data
            cairo-surface-get-user-data
            CAIRO_SVG_VERSION_1_1
            CAIRO_SVG_VERSION_1_2
            cairo-svg-surface-create
            cairo-svg-surface-create-for-stream
            cairo-svg-surface-restrict-to-version
            cairo-svg-version-to-string
            CAIRO_FORMAT_ARGB32
            CAIRO_FORMAT_RGB24
            CAIRO_FORMAT_A8
            CAIRO_FORMAT_A1
            CAIRO_FORMAT_RGB16_565
            CAIRO_FONT_SLANT_NORMAL
            CAIRO_FONT_SLANT_ITALIC
            CAIRO_FONT_SLANT_OBLIQUE
            CAIRO_FONT_WEIGHT_NORMAL
            CAIRO_FONT_WEIGHT_BOLD
            CAIRO_TEXT_CLUSTER_FLAG_BACKWARD
            cairo-select-font-face
            cairo-set-font-size
            cairo-set-font-matrix
            cairo-get-font-matrix
            cairo-set-font-options
            cairo-get-font-options
            cairo-set-font-face
            cairo-get-font-face
            cairo-set-scaled-font
            cairo-get-scaled-font
            cairo-show-text
            cairo-show-glyphs
            cairo-font-extents
            cairo-text-extents
            cairo-glyph-extents
            cairo-translate
            cairo-scale
            cairo-rotate
            cairo-transform
            cairo-set-matrix
            cairo-get-matrix
            cairo-identity-matrix
            cairo-user-to-device
            cairo-user-to-device-distance
            cairo-device-to-user
            cairo-device-to-user-distance
            CAIRO_FORMAT_ARGB32
            CAIRO_FORMAT_RGB24
            CAIRO_FORMAT_A8
            CAIRO_FORMAT_A1
            CAIRO_FORMAT_RGB16_565
            XOpenDisplay
            XCloseDisplay
            DefaultScreen
            DefaultRootWindow
            XCreateSimpleWindow
            XMapWindow
            DefaultVisual
            window->drawable
            XSelectInput
            XFlush
            ButtonPressMask
            KeyPressMask
            cairo-create-x11-surface
            cairo-destroy-x11-surface
            cairo-x11-pump-events
            cairo-x11-display-pump-events
            cairo-xlib-surface-create
            cairo-xlib-surface-create-for-bitmap
            cairo-xlib-surface-set-size
            cairo-xlib-surface-get-display
            cairo-xlib-surface-get-screen
            cairo-xlib-surface-set-drawable
            cairo-xlib-surface-get-drawable
            cairo-xlib-surface-get-visual
            cairo-xlib-surface-get-width
            cairo-xlib-surface-get-height
            cairo-xlib-surface-get-depth
            ))
